### ISSUE TITLE
Error in lambda create

### ISSUE THREAD

**Issue by acourter27** [marksteele/self-destruct-o#2]
I'm getting this error for IndexLambdaFunction, CreateLambdaFunction, and GetLambdaFunction:

Resource handler returned message: "The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions.

**Comment by marksteele** [comment]
Bumped the version, pull from master and give it another go
