### ISSUE TITLE
Installation procedure got warnings and errors with "npm" command

### ISSUE THREAD

**Issue by Wikiphil** [marksteele/self-destruct-o#3]
Hi,

I really trust the way that you explain your project! I want to deploy it and test it, but "npm" command gave my errors. Can you help me in the deployment or fix the script with the new version of the commands?

My result:
[cloudshell-user@ip-10-0-82-226 node_modules]$ npm i serverless -g
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (../../home/cloudshell-user/node_modules/serverless/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cloudshell-user/.npm/_logs/2021-05-16T21_28_39_882Z-debug.log

Regards.

**Comment by Wikiphil** [comment]
UPDATE: running "sudo npm i serverless -g" fixes lot of issues.

Last issue:  An error occurred: GetLambdaFunction - Resource handler returned message: "The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: f9b83449-5891-4716-ba47-83ce207e99df, Extended Request ID: null)" (RequestToken: 35ee9906-b0e6-0818-4f6f-5310f15d4d60, HandlerErrorCode: InvalidRequest).

**Comment by marksteele** [comment]
Bumped the nodejs version, might work now :)

Pull from master and give it a go
