### ISSUE TITLE
key id of 'foo'

### ISSUE THREAD

**Issue by acourter27** [marksteele/self-destruct-o#4]
When I built the app it used the key ID of "foo" everywhere. I was able to manually edit that in the 3 lambdas and in the AssumedRole.

I noticed the SSM didn't have the right KeyID selected, so I changed that as well.

I'm not sure if it was thrown off during the build, or because this was my 2nd attempt at doing this and I did an --overwrite command on the SMS piece.

At this point I have it running, so feel free to close this if it was something I did. Otherwise just wanted to let you know.

I love the app - good work.

**Comment by marksteele** [comment]
Yup, that's why it flaked out..
